Sprint2
oier-elorrieta/R3-JOEL-MIKEL-UNAI pull request #2
Opened 2021-02-08 10:04 UTC by joelfano

Emen bigarren sprinta. Zure erantzunaren zain egongo gara.

2021-02-09 11:37 UTC, oier-elorrieta requested changes
Aldaketa hauek egin behar dituzue, baina gehiago egon daitezke

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelErregistratu.java
> +
Kendu ezertarako balio ez duten lerro zuri hauek

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelFaktura.java
> +	public int TransferentziaZenbakia() {
metodoak letra txikiz hasten dira.  Hainbat dauzkazue letra larriz jarrita. Horrela izendatuta eraikitzaile bat ematen du. Zer da? datu bat jasotzen du? Ba aldatu izena jaso.../get...

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/Modelo.java
> -	public ArrayList<Karritoa> ezabatu(){
Metodo honi aldatu ahal diozue izena, jakiteko zer ezabatzen den?

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelEskaera.java
>  		return this.modelo.produktuakJaso();
Metodoak letra txikiz hasi behar dira

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelEskaera.java
> +		return this.modelo.TranferentziaZbk();
MEtodoak letra txikiz hasi behar dira. MEtodo horrek eraikitzaile bat ematen du? Zer egiten du? Jaso.../get... Eman izen adierazgarriagoa....

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelFaktura.java
> +		this.modelo.ezabatu();
ezabatu metodoan aldatu izena jakiteko zer ezabatzen den

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelLaburpena.java
> +		return this.modelo.komprobatuLokalarenIzena();
txorrada bat. Euskaraz p aurretik ez doa m

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelTicket.java
> +		return this.modelo.TranferentziaZbk();
Metodoen izenak: minuskulaz eta esanguratsuagoak

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/Modelo.java
> +	public ArrayList<Karritoa> kk(ArrayList<Karritoa> karroa) {
Aldatu izena eta behar ez bada (ziurrena), ezabatu.

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/Modelo.java
> +	private int TransferentziaZbk = 1;
Hobetu datu basean atzipenarekin. TransferentziaZbk datu basetik hartu.

2021-02-09 11:37 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/Modelo.java
> +	private String NIF = null;
NIF-a behar baduzue, egin garraiatzea pantailen artean

2021-02-09 12:00 UTC, oier-elorrieta requested changes
Aldaketa hauek egin behar dituzue, baina gehiago egon daitezke

2021-02-09 12:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoak.java
> +			String LokalarenIzena = null;
aldagaiak minuskulaz

2021-02-09 12:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Vista/PanelErregistratu.java
> +				String NIF = TF_NIF.getText();
minus

2021-02-09 12:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Vista/PanelLogin.java
> +				String ErroreaLogeatzean = controladorPanelLogin.konprobatuErabiltzailea(erabiltzailea, pasahitza);
aldagaiak minus

2021-02-09 12:22 UTC, joelfano commented on Ethazi3/src/main/java/Controlador/ControladorPanelErregistratu.java
> +
Eginda

2021-02-09 12:23 UTC, joelfano commented on Ethazi3/src/main/java/Controlador/ControladorPanelFaktura.java
> +	public int TransferentziaZenbakia() {
Kendu dugu

2021-02-09 12:23 UTC, joelfano commented on Ethazi3/src/main/java/Controlador/ControladorPanelEskaera.java
>  		return this.modelo.produktuakJaso();
Eginda

2021-02-09 12:24 UTC, joelfano commented on Ethazi3/src/main/java/Controlador/ControladorPanelEskaera.java
> +		return this.modelo.TranferentziaZbk();
Kenduko dugu

2021-02-09 12:24 UTC, joelfano commented on Ethazi3/src/main/java/Vista/PanelLogin.java
> +				String ErroreaLogeatzean = controladorPanelLogin.konprobatuErabiltzailea(erabiltzailea, pasahitza);
Eginda

2021-02-09 12:24 UTC, joelfano commented on Ethazi3/src/main/java/Vista/PanelErregistratu.java
> +				String NIF = TF_NIF.getText();
Eginda

2021-02-09 12:24 UTC, joelfano commented on Ethazi3/src/main/java/Modelo/metodoak.java
> +			String LokalarenIzena = null;
Eginda

2021-02-09 12:24 UTC, joelfano commented on Ethazi3/src/main/java/Modelo/Modelo.java
> +	public ArrayList<Karritoa> kk(ArrayList<Karritoa> karroa) {
Eginda

2021-02-09 12:24 UTC, joelfano commented on Ethazi3/src/main/java/Controlador/ControladorPanelTicket.java
> +		return this.modelo.TranferentziaZbk();
Kenduko dugu

2021-02-10 07:32 UTC, joelfano commented on Ethazi3/src/main/java/Modelo/Modelo.java
> -	public ArrayList<Karritoa> ezabatu(){
Eginda

2021-02-10 07:32 UTC, joelfano commented on Ethazi3/src/main/java/Controlador/ControladorPanelLaburpena.java
> +		return this.modelo.komprobatuLokalarenIzena();
Eginda

2021-02-10 07:32 UTC, joelfano commented on Ethazi3/src/main/java/Modelo/Modelo.java
> +	private int TransferentziaZbk = 1;
Eginda

2021-02-10 07:32 UTC, joelfano commented on Ethazi3/src/main/java/Modelo/Modelo.java
> +	private String NIF = null;
Eginda

2021-02-11 11:39 UTC, oier-elorrieta approved these changes
Oneritzia ematen dizuet

2021-02-11 11:41 UTC, merged