Sprint3
oier-elorrieta/R3-JOEL-MIKEL-UNAI pull request #3
Opened 2021-03-07 18:25 UTC by joelfano

Emen Sprint3

2021-03-10 11:00 UTC, oier-elorrieta requested changes
Kendu ñ-ak, sysoak, lerro txuriak eta saiatu metodoen izenak apur bat deskriptiboagoak egiten.

Bestela oso ondo dago.

Horrela jarraitu!!!!

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelEskaera.java
> +	public void gordeEskaera(String helbidea, int a�o, int mes, int dia) throws ClassNotFoundException, SQLException {
ñ letra ez da erabilgarria informatikan.

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelFaktura.java
> +	public void sartuFaktura(String izena, String abizena, int a�o, int mes, int dia) throws ClassNotFoundException, SQLException {
ñ letra

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelKomanda.java
> +	public void ofrece() {
Ez da argi geratzen zer egiten duten metodo batzuk. Aditzak sartuta, hobeto.

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Controlador/ControladorPanelTicket.java
> +	public void gordeTicket(int a�o, int mes, int dia) throws ClassNotFoundException, SQLException {
ñ

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakFaktura.java
> +
soberako lerroak kendu

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakFaktura.java
> +			System.out.println("Errorea konexioan");
Sysoak kendu

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakFaktura.java
> +
espazioa

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakHornikuntza.java
> +			e.printStackTrace();
Syso

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakKonprobaketak.java
> +
lerroa

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakKonprobaketak.java
> +
lerroa

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakKonprobaketak.java
> +			System.out.println("Errorea konexioan");
Syso

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakPlaterrakEtaProduktuak.java
> +
lerro txuri asko!!!

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/main/java/Modelo/metodoakPlaterrakEtaProduktuak.java
> +
lerro txuri asko!!!

2021-03-10 11:00 UTC, oier-elorrieta commented on Ethazi3/src/test/java/TestModelo/ModeloTestKonprobaketak.java
> +
lerro txuriak!!!

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Controlador/ControladorPanelEskaera.java
> +	public void gordeEskaera(String helbidea, int a�o, int mes, int dia) throws ClassNotFoundException, SQLException {
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Controlador/ControladorPanelFaktura.java
> +	public void sartuFaktura(String izena, String abizena, int a�o, int mes, int dia) throws ClassNotFoundException, SQLException {
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Controlador/ControladorPanelKomanda.java
> +	public void ofrece() {
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Controlador/ControladorPanelTicket.java
> +	public void gordeTicket(int a�o, int mes, int dia) throws ClassNotFoundException, SQLException {
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Modelo/metodoakFaktura.java
> +
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Modelo/metodoakKonprobaketak.java
> +
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Modelo/metodoakKonprobaketak.java
> +			System.out.println("Errorea konexioan");
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Modelo/metodoakPlaterrakEtaProduktuak.java
> +
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/main/java/Modelo/metodoakPlaterrakEtaProduktuak.java
> +
zuzenduta

2021-03-12 11:04 UTC, unaihernando commented on Ethazi3/src/test/java/TestModelo/ModeloTestKonprobaketak.java
> +
zuzenduta

2021-03-12 11:52 UTC, oier-elorrieta approved these changes
Ondo eginda. Azken sprinterako ñ guztiak kanpora

2021-03-12 11:52 UTC, merged